# Write your query or mutation here
query ALL_VRACHI_PROMO($ID: String) {
  orders(filters: { PromoVrach: { eq: $ID } }) {
    data {
      id
      attributes {
        SummOrder
        createdAt
      }
    }
  }
}
