query ORDERS( $PAGE: Int! , $GTE: DateTime, $LTE: DateTime) {
  orders(pagination: { pageSize: 10, page: $PAGE }, sort: "Status:asc") {
    meta {
      pagination {
        total
        pageSize
        pageCount
        page
      }
    }
    data {
      id
      attributes {
        Status
        SummOrder
        StatusOplata
        UID
        users {
          data {
            id
            attributes {
              FIO_user
            }
          }
        }
        analizies {
          data {
            id
            attributes {
              UID
            }
          }
        }
      }
    }
  }
}
