query SEARCH_PACIENT($FIO: String) {
  usersPermissionsUsers(filters: { FIO_user: { containsi: $FIO } and : {RoleUser : {eq : "Pacient"}} }) {
    data {
      id
      attributes {
        FIO_user
      }
    }
  }
}
