query($FIO: String!) {
    search(query: $FIO) {
      vrachis {
        data {
          id
          attributes {
            FIO
            users_permissions_user {
              data {
                id
                attributes {
                  speczialnosts {
                    data {
                      attributes {
                        Name
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }